<a href="https://colab.research.google.com/github/bennng/scikit-learn/blob/master/raw_notes_data_cleaning_scklearn_linear_regression_and_decision_tree_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Import pandas. Pandas is a very useful library to work with and to manipulate data. Much of my time in data science is actually working with this particular library when examining and cleaning data sets 

import pandas as pd
from google.colab import files
#uploaded = files.upload()
!wget https://raw.githubusercontent.com/bennng/data/master/automobile.csv


--2020-02-05 08:34:43--  https://raw.githubusercontent.com/bennng/data/master/automobile.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25053 (24K) [text/plain]
Saving to: ‘automobile.csv’

automobile.csv      100%[===================>]  24.47K  --.-KB/s    in 0.01s   

2020-02-05 08:34:44 (1.96 MB/s) - ‘automobile.csv’ saved [25053/25053]



In [0]:
# I set some missing values to look out for in my data set and then I read the file with read_csv. 
# Once read I print out the number of records that has the missing values I set with the variable missing_values.
# Note the other code I commented out which deal with alternative ways to grab the data file.
missing_values = ["NaN","n/a", "na", "--", "?"]
#import io
#df = pd.read_csv(io.BytesIO(uploaded['automobile.csv']),  na_values = missing_values)
df = pd.read_csv('automobile.csv',  na_values=missing_values)
#print (df['Num-of-doors'])
#print (df['Num-of-doors'].isnull())
print (df.isnull().sum())

Id                   41
Make                  0
Fuel-type             0
Aspiration            0
Num-of-doors          2
Body-style            0
Drive-wheels          0
Engine-location       0
Wheel-base            0
Length                0
Width                 0
Height                0
Curb-weight           0
Engine-type           0
Num-of-cylinders      0
Engine-size           0
Fuel-system           0
Bore                  4
Stroke                4
Compression-ratio     0
Horsepower            2
Peak-rpm              2
City-mpg              0
Highway-mpg           0
Price                 4
Symboling             0
dtype: int64


In [0]:
#Cleaning data: In most data sets you find you will always run into the problem of missing data.
#Always research the data. I see what I can do to fill in the missing data. Sometimes  I talk with stake holders. Sometime i might talk to other SMEs. 
# Sometime I will try to find the missing data from another datasource, perhaps a different database. 
#Case in point here we are looking at data dealing with automobiles. If there is missing data about the number of doors I might just go to the car makers website and look up the car. 
# I would then proceed to fill out that data if I can. If there are no other choices you can delete or use the mean, median or mode of that set.

doorsmode = df['Num-of-doors'].mode()
doorsmode
df['Num-of-doors'].fillna(doorsmode, inplace=True)

boremedian = df['Bore'].median()
boremedian
df['Bore'].fillna(boremedian, inplace=True)

strokemedian = df['Stroke'].median()
strokemedian
df['Stroke'].fillna(strokemedian, inplace=True)

hpmedian = df['Horsepower'].median()
hpmedian
df['Horsepower'].fillna(hpmedian, inplace=True)

rpmode = df['Peak-rpm'].median()
rpmode
df['Peak-rpm'].fillna(rpmode, inplace=True)

pricemedian = df['Price'].median()
pricemedian
df['Price'].fillna(pricemedian, inplace=True)

df.loc[4,'Num-of-doors'] = 'four'
df.loc[171,'Num-of-doors'] = 'four'

print (df.isnull().sum())
#print(df['Make'].unique())



Id                   41
Make                  0
Fuel-type             0
Aspiration            0
Num-of-doors          0
Body-style            0
Drive-wheels          0
Engine-location       0
Wheel-base            0
Length                0
Width                 0
Height                0
Curb-weight           0
Engine-type           0
Num-of-cylinders      0
Engine-size           0
Fuel-system           0
Bore                  0
Stroke                0
Compression-ratio     0
Horsepower            0
Peak-rpm              0
City-mpg              0
Highway-mpg           0
Price                 0
Symboling             0
dtype: int64
['toyota' 'mazda' 'mitsubishi' 'dodge' 'nissan' 'jaguar' 'peugot'
 'chevrolet' 'bmw' 'volkswagen' 'plymouth' 'isuzu' 'mercury' 'subaru'
 'audi' 'honda' 'mercedes-benz' 'renault' 'saab' 'volvo' 'alfa-romero'
 'porsche']


In [0]:
# Here I sort the set based on the Id and see what I can do about the missing Ids
df.sort_values('Id', axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last')
#df.head(20)
print(df.to_string())


        Id           Make Fuel-type Aspiration Num-of-doors   Body-style Drive-wheels Engine-location  Wheel-base  Length  Width  Height  Curb-weight Engine-type Num-of-cylinders  Engine-size Fuel-system  Bore  Stroke  Compression-ratio  Horsepower  Peak-rpm  City-mpg  Highway-mpg    Price  Symboling
200   65.0         toyota       gas        std         four        sedan          fwd           front       102.4   175.6   66.5    54.9         2414         ohc             four          122        mpfi  3.31    3.54               8.70        92.0    4200.0        27           32  10898.0         -1
120   65.0         toyota       gas        std         four        sedan          fwd           front       102.4   175.6   66.5    54.9         2326         ohc             four          122        mpfi  3.31    3.54               8.70        92.0    4200.0        29           34   8948.0         -1
80    65.0         toyota       gas        std         four    hatchback          fwd         

In [0]:
#I see that the Ids missing pertaining has a Make associated. 
#In the set there are some records with the same Make that has Ids. Also the Ids can repeat. 
#If there are no other resources that can help to fill in this data I can deduce the missing Ids based on the Make and existing Ids.
#I modify each NaN record based on these assumptions.
    
df.loc[191,'Id'] = 94
df.loc[123,'Id'] = 256
df.loc[133,'Id'] = 256
df.loc[121,'Id'] = 134
df.loc[170,'Id'] = 186
df.loc[166,'Id'] = 186
df.loc[132,'Id'] = 186
df.loc[90,'Id'] = 186
df.loc[18,'Id'] = 119
df.loc[124,'Id'] = 161
df.loc[136,'Id'] = 161
df.loc[115,'Id'] = 161
df.loc[30,'Id'] = 161
df.loc[77,'Id'] = 192 #bmw
df.loc[19,'Id'] = 192 #bmw
df.loc[45,'Id'] = 192 #bmw
df.loc[96,'Id'] = 192 #bmw
df.loc[53,'Id'] = 192 #bmw
df.loc[31,'Id'] = 164 #audi
df.loc[108,'Id'] = 164 #audi
df.loc[119,'Id'] = 164 #audi

df.loc[112,'Id'] = 104 #mazda
df.loc[171,'Id'] = 104 #mazda
df.loc[175,'Id'] = 142#mercedes-benz
df.loc[201,'Id'] = 142 #mercedes-benz
df.loc[43,'Id'] = 142 #mercedes-benz
df.loc[22,'Id'] = 261 #mercury
df.loc[151,'Id'] = 153 #mitsubishi
df.loc[147,'Id'] = 153 #mitsubishi
df.loc[123,'Id'] = 153 #mitsubishi
df.loc[47,'Id'] = 153 #mitsubishi
df.loc[27,'Id'] = 153 #mitsubishi
df.loc[154,'Id'] = 94 #volkswagen


df.loc[62,'Id'] = 257  #renault
df.loc[40,'Id'] = 257   #renault
df.loc[7,'Id'] = 258   #jaguar
df.loc[29,'Id'] = 258  #jaguar
df.loc[142,'Id'] = 259  #isuzu
df.loc[21,'Id'] = 259 #isuzu
df.loc[113,'Id'] = 259 #isuzu   
df.loc[71,'Id'] = 259  #isuzu
df.loc[131,'Id'] = 260  #alfa-romero
df.loc[68,'Id'] = 260  #alfa-romero
df.loc[190,'Id'] = 260 #alfa-romero

In [0]:
# I print out again the sorted set to verify that no further missing data is present.

df.sort_values('Id', axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last')
#df.head(20)
print(df.to_string())

print (df.isnull().sum())


        Id           Make Fuel-type Aspiration Num-of-doors   Body-style Drive-wheels Engine-location  Wheel-base  Length  Width  Height  Curb-weight Engine-type Num-of-cylinders  Engine-size Fuel-system  Bore  Stroke  Compression-ratio  Horsepower  Peak-rpm  City-mpg  Highway-mpg    Price  Symboling
200   65.0         toyota       gas        std         four        sedan          fwd           front       102.4   175.6   66.5    54.9         2414         ohc             four          122        mpfi  3.31    3.54               8.70        92.0    4200.0        27           32  10898.0         -1
120   65.0         toyota       gas        std         four        sedan          fwd           front       102.4   175.6   66.5    54.9         2326         ohc             four          122        mpfi  3.31    3.54               8.70        92.0    4200.0        29           34   8948.0         -1
80    65.0         toyota       gas        std         four    hatchback          fwd         

In [0]:
# I don't like '-' in my data set so I modify the header to not have them

makedummies = pd.get_dummies(df.Make)
makemergeddf = pd.concat([df, makedummies], axis='columns')
dropdummytrapmakemergeddf = makemergeddf.drop(['Make','alfa-romero'], axis='columns')
#dropdummytrapmakemergeddf

dropdummytrapmakemergeddf.rename(columns = {'Fuel-type':'Fueltype'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Num-of-doors':'Doors'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Body-style':'Body'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Drive-wheels':'Wheeldrive'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Engine-location':'Enginelocation'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Wheel-base':'Wheelbase'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Curb-weight':'Curbweight'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Engine-type':'Enginetype'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Num-of-cylinders':'Numofcylinders'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Engine-size':'Enginesize'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Fuel-system':'Fuelsystem'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Compression-ratio':'Compressionratio'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Peak-rpm':'Peakrpm'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'City-mpg':'Citympg'}, inplace = True)
dropdummytrapmakemergeddf.rename(columns = {'Highway-mpg':'Highwaympg'}, inplace = True)

dropdummytrapmakemergeddf.rename(columns = {'mercedes-benz':'mercedesbenz'}, inplace = True)

dropdummytrapmakemergeddf

Id Fueltype Aspiration Doors  ... subaru toyota volkswagen  volvo
200   65.0      gas        std  four  ...      0      1          0      0
120   65.0      gas        std  four  ...      0      1          0      0
80    65.0      gas        std  four  ...      0      1          0      0
161   65.0   diesel      turbo  four  ...      0      1          0      0
17    65.0      gas        std  four  ...      0      1          0      0
..     ...      ...        ...   ...  ...    ...    ...        ...    ...
71   259.0      gas        std  four  ...      0      0          0      0
68   260.0      gas        std   two  ...      0      0          0      0
190  260.0      gas        std   two  ...      0      0          0      0
131  260.0      gas        std   two  ...      0      0          0      0
22   261.0      gas      turbo   two  ...      0      0          0      0

[205 rows x 46 columns]

DataSet is now clean. Time to Normalize.


In [0]:

fueltypedf = pd.get_dummies(dropdummytrapmakemergeddf.Fueltype)
df1 = pd.concat([dropdummytrapmakemergeddf, fueltypedf], axis='columns')
df2 = df1.drop(['Fueltype','diesel'], axis='columns')
#df2
#fueltypedf

aspirationdf = pd.get_dummies(df2.Aspiration)
df3 = pd.concat([df2, aspirationdf], axis='columns')
df4 = df3.drop(['Aspiration','turbo'], axis='columns')
#df4
#df3

Doorsdf = pd.get_dummies(df4.Doors)
df5 = pd.concat([df4, Doorsdf], axis='columns')
df6 = df5.drop(['Doors','two'], axis='columns')
#df6

Bodydf = pd.get_dummies(df6.Body)
df7 = pd.concat([df6, Bodydf], axis='columns')
df8 = df7.drop(['Body','hatchback'], axis='columns')
#df8

Wheeldrivedf = pd.get_dummies(dropdummytrapmakemergeddf.Wheeldrive)
df9 = pd.concat([df8, Wheeldrivedf], axis='columns')
df10 = df9.drop(['Wheeldrive','fwd'], axis='columns')
#df10

Enginelocationdf = pd.get_dummies(dropdummytrapmakemergeddf.Enginelocation)
df11 = pd.concat([df10, Enginelocationdf], axis='columns')
df12 = df11.drop(['Enginelocation','front'], axis='columns')


Enginetypedf = pd.get_dummies(dropdummytrapmakemergeddf.Enginetype)
df13 = pd.concat([df12, Enginetypedf], axis='columns')
df14 = df13.drop(['Enginetype','ohcv'], axis='columns')


Numofcylindersdf	 = pd.get_dummies(dropdummytrapmakemergeddf.Numofcylinders)
df15 = pd.concat([df14, Numofcylindersdf], axis='columns')
df16 = df15.drop(['Numofcylinders','six'], axis='columns')

Fuelsystemdf = pd.get_dummies(dropdummytrapmakemergeddf.Fuelsystem)
df17 = pd.concat([df16, Fuelsystemdf], axis='columns')
df18 = df17.drop(['Fuelsystem','idi'], axis='columns')








In [0]:
df18

Id  Wheelbase  Length  Width  Height  ...  4bbl  mfi  mpfi  spdi  spfi
200   65.0      102.4   175.6   66.5    54.9  ...     0    0     1     0     0
120   65.0      102.4   175.6   66.5    54.9  ...     0    0     1     0     0
80    65.0      102.4   175.6   66.5    53.9  ...     0    0     1     0     0
161   65.0      102.4   175.6   66.5    54.9  ...     0    0     0     0     0
17    65.0      102.4   175.6   66.5    53.9  ...     0    0     1     0     0
..     ...        ...     ...    ...     ...  ...   ...  ...   ...   ...   ...
71   259.0       94.3   170.7   61.8    53.5  ...     0    0     0     0     0
68   260.0       88.6   168.8   64.1    48.8  ...     0    0     1     0     0
190  260.0       88.6   168.8   64.1    48.8  ...     0    0     1     0     0
131  260.0       94.5   171.2   65.5    52.4  ...     0    0     1     0     0
22   261.0      102.7   178.4   68.0    54.8  ...     0    0     1     0     0

[205 rows x 66 columns]

In [0]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

X = df18.drop('Symboling', axis='columns')
X

Y = df18.Symboling

#print(df18.to_string())


        Id  Wheelbase  Length  Width  Height  Curbweight  Enginesize  Bore  Stroke  Compressionratio  Horsepower  Peakrpm  Citympg  Highwaympg    Price  Symboling  audi  bmw  chevrolet  dodge  honda  isuzu  jaguar  mazda  mercedesbenz  mercury  mitsubishi  nissan  peugot  plymouth  porsche  renault  saab  subaru  toyota  volkswagen  volvo  gas  std  four  convertible  hardtop  sedan  wagon  4wd  rwd  rear  dohc  dohcv  l  ohc  ohcf  rotor  eight  five  four  three  twelve  two  1bbl  2bbl  4bbl  mfi  mpfi  spdi  spfi
200   65.0      102.4   175.6   66.5    54.9        2414         122  3.31    3.54              8.70        92.0   4200.0       27          32  10898.0         -1     0    0          0      0      0      0       0      0             0        0           0       0       0         0        0        0     0       0       1           0      0    1    1     1            0        0      1      0    0    0     0     0      0  0    1     0      0      0     0     1      0       0 

In [0]:
model.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
import pickle
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
model.predict([[65.00,102.4,175.6,66.5,54.9,2414,122,3.31,3.54,8.70,92.0,4200.0,27,32,10898.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0]])

array([-0.79713045])

In [0]:
model.predict([[94.0,97.3,171.7,65.5,55.7,2275,109,3.19,3.40,9.00,85.0,5250.0,27,34,8495.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0]])

array([1.44079657])

In [0]:
model.predict([[94.0,97.3,171.7,65.5,55.7,2275,109,3.19,3.40,9.00,85.0,5250.0,27,34,10495.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0]])

array([1.44134944])

In [0]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X, Y)
print(result)

0.8479967456470089


In [0]:
loaded_model.predict([[94.0,97.3,171.7,65.5,55.7,2275,109,3.19,3.40,9.00,85.0,5250.0,27,34,10495.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0]])

array([1.44134944])

In [0]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X,Y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [0]:
import numpy as np

from sklearn.metrics import mean_squared_error
symboling_predictions = tree_reg.predict(X)
tree_mse = mean_squared_error(Y, symboling_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.0

In [0]:
tree_reg.predict([[65.00,102.4,175.6,66.5,54.9,2414,122,3.31,3.54,8.70,92.0,4200.0,27,32,10898.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0]])

array([-1.])

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree_reg, X, Y, scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

def display_scores(scores):
  print("Scores:", scores)
  print("Mean:", scores.mean())
  print("Standard deviation:", scores.std())

display_scores(tree_rmse_scores)

Scores: [0.9258201  0.53452248 0.         0.97590007 0.78679579 1.22474487
 1.28452326 0.83666003 1.54919334 1.20415946]
Mean: 0.9322319401169752
Standard deviation: 0.41517728894330447
